version: '3.8'
services:
  test:
    image: ubuntu:latest
    command: ["echo", "This is a test environment"]
    environment:
      - TEST_ENV_VAR=exampleaaaaa
  blender:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PATH=/usr/local/cuda-12.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:/usr/local/lib:/usr/lib
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]